INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(1,'Phillip','Patricia','faucibus leo, in',25-05-08);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(2,'Elmo','Justin','malesuada ut, sem.',28-04-18);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(3,'Gretchen','Britanney','felis ullamcorper viverra.',23-10-14);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(4,'Kathleen','Noah','risus, at fringilla',15-11-15);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(5,'Imogene','Donovan','Nulla tincidunt, neque',30-10-19);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(6,'Eleanor','Jameson','magnis dis parturient',14-04-15);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(7,'Joshua','Rudyard','odio a purus.',13-05-19);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(8,'Georgia','Jade','Quisque ornare tortor',09-07-20);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(9,'Matthew','Kay','ullamcorper, velit in',14-01-10);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(10,'Cassandra','Emerson','in sodales elit',08-04-13);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(11,'Nehru','Driscoll','arcu eu odio',16-03-17);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(12,'Yeo','Kessie','In at pede.',16-03-09);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(13,'April','Ryder','sodales at, velit.',12-04-21);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(14,'Dennis','Lucian','ultrices, mauris ipsum',21-05-17);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(15,'Neville','Oliver','lorem, auctor quis,',12-05-09);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(16,'Rina','Germane','enim. Nunc ut',19-11-20);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(17,'Jeanette','Hayden','mollis lectus pede',20-02-19);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(18,'Salvador','Riley','sociis natoque penatibus',10-04-09);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(19,'Kermit','Eleanor','ornare, lectus ante',17-02-18);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(20,'Harper','Coby','ipsum dolor sit',09-09-09);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(21,'Brooke','Quentin','scelerisque scelerisque dui.',18-02-21);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(22,'Dante','Kirestin','luctus sit amet,',12-08-11);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(23,'Claire','Vance','Aliquam rutrum lorem',01-03-16);
INSERT INTO cliente([dpi],[nombre],[apellido],[direccion],[fechaNacimiento]) VALUES(24,'Lucius','Jared','sit amet luctus',16-11-18);

select * from cliente;
