INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(1,'994-323 Dictum Avenue','Morbi Quis Urna Industries');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(2,'818-9394 Lorem Av.','Quis Incorporated');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(3,'Ap #804-3738 Congue St.','Lacus Ut Nec Ltd');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(4,'4236 Nec, Street','Neque Nullam Industries');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(5,'231-4151 Amet St.','Et Inc.');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(6,'4259 Feugiat. Road','Magna Ltd');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(7,'6958 Magna. Ave','Accumsan Neque Corporation');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(8,'7147 Ridiculus Rd.','Enim Industries');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(9,'Ap #810-6007 Amet Road','Rutrum Magna Associates');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(10,'Ap #604-3618 Orci Av.','Suspendisse Sagittis Nullam LLC');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(11,'186-3540 Ornare, St.','Litora Torquent Incorporated');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(12,'5454 Egestas, Rd.','Etiam LLP');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(13,'179-5265 Amet Avenue','Egestas Nunc Sed Ltd');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(14,'Ap #488-7063 Et St.','Aliquam Fringilla Cursus PC');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(15,'P.O. Box 421, 7378 Quis, Rd.','Purus Nullam Associates');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(16,'444-3502 Nunc Rd.','Magna Tellus Consulting');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(17,'8343 Ipsum St.','Scelerisque Neque LLP');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(18,'Ap #426-772 Lacus. St.','Eget Lacus LLP');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(19,'8913 Scelerisque Street','Sit Amet Corporation');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(20,'Ap #555-5680 Sapien. St.','Donec Tempus Lorem Consulting');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(21,'8056 Eros Rd.','Sociis PC');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(22,'Ap #618-2690 Tellus Street','Congue Ltd');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(23,'7298 Sit Rd.','Suspendisse Commodo Ltd');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(24,'Ap #714-7602 Et St.','Rutrum Magna Incorporated');
INSERT INTO proveedor([nit],[Direccion],[Nombre]) VALUES(25,'620-455 Nunc. Street','Egestas Rhoncus Inc.');
select * from proveedor;